version: 2.1

jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Debug current directory
          command: pwd && ls -R
      - run:
          name: Create test results directory
          command: mkdir -p test_results
      - run:
          name: Run tests
          command: python -m unittest discover -s simple_calculator -p "test_*.py" -v > test_results/results.xml
      - store_test_results:
          path: test_results

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
