version: 2.1

jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Run tests
          command: python -m unittest discover

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
